kumuluzee:
  name: genre-service
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8083
    http:
      port: 8083
  datasources:
    - jndi-name: jdbc/GenresDS
      connection-url: jdbc:postgresql://localhost:5433/genre
      username: postgres
      password: postgres
      max-pool-size: 20
#  config:
#    etcd:
#      hosts: http://192.168.99.100:2379
#  discovery:
#    etcd:
#      hosts: http://192.168.99.100:2379

  rest-properties:
    external-dependencies:
      band-service:
        enabled: true
