apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: postgres-genre-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : postgres-genre
    spec:
      containers:
        - image: centos/postgresql-94-centos7
          name: postgres-genre
          env:
            - name: POSTGRESQL_USER
              value: userdb
            - name: POSTGRESQL_PASSWORD
              value: postgres
            - name: POSTGRESQL_DATABASE
              value: genre
          ports:
          - containerPort: 5432
            protocol: TCP
