apiVersion: v1
kind: Service
metadata:
  name: postgres-genre
spec:
  type: ClusterIP
  ports:
  - port: 5434 #<-na vem
    protocol: TCP
    targetPort: 5432 #<-original
  selector:
    app: postgres-genre
